version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: twitch_defi
    ports:
      - '3306:3306'
